[features]
seeds = false
skip-lint = false
[programs.localnet]
ride_network = "AdzUEnPqSShvbkMyEsPuz1AZGaKdb6x9kH3hbbtEvKym"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/justinlee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
